### ISSUE TITLE
macos python3.9无法安装

### ISSUE THREAD

**Issue by zhajingwen** [kuangdd/ttskit#12]
Building wheels for collected packages: llvmlite
  Building wheel for llvmlite (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [26 lines of output]
      running bdist_wheel
      /Library/Frameworks/Python.framework/Versions/3.9/bin/python3 /private/var/folders/yn/4byzlmls27n1sn4b19pwp6nm0000gn/T/pip-install-o9dwgbtj/llvmlite_14beb0db95e84b99a61cb1db7d4980bb/ffi/build.py
      LLVM version... Traceback (most recent call last):
        File "/private/var/folders/yn/4byzlmls27n1sn4b19pwp6nm0000gn/T/pip-install-o9dwgbtj/llvmlite_14beb0db95e84b99a61cb1db7d4980bb/ffi/build.py", line 105, in main_posix
          out = subprocess.check_output([llvm_config, '--version'])
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 424, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 505, in run
          with Popen(*popenargs, **kwargs) as process:
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 951, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1821, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/private/var/folders/yn/4byzlmls27n1sn4b19pwp6nm0000gn/T/pip-install-o9dwgbtj/llvmlite_14beb0db95e84b99a61cb1db7d4980bb/ffi/build.py", line 168, in <module>
          main()
        File "/private/var/folders/yn/4byzlmls27n1sn4b19pwp6nm0000gn/T/pip-install-o9dwgbtj/llvmlite_14beb0db95e84b99a61cb1db7d4980bb/ffi/build.py", line 162, in main
          main_posix('osx', '.dylib')
        File "/private/var/folders/yn/4byzlmls27n1sn4b19pwp6nm0000gn/T/pip-install-o9dwgbtj/llvmlite_14beb0db95e84b99a61cb1db7d4980bb/ffi/build.py", line 107, in main_posix
          raise RuntimeError("%s failed executing, please point LLVM_CONFIG "
      RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
      error: command '/Library/Frameworks/Python.framework/Versions/3.9/bin/python3' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llvmlite
  Running setup.py clean for llvmlite
Failed to build llvmlite
Installing collected packages: llvmlite, zope.interface, zope.event, torch, numba, greenlet, matplotlib, gevent, umap-learn, ttskit
  Attempting uninstall: llvmlite
    Found existing installation: llvmlite 0.38.0
    Uninstalling llvmlite-0.38.0:
      Successfully uninstalled llvmlite-0.38.0
  Running setup.py install for llvmlite ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for llvmlite did not run successfully.
  │ exit code: 1
  ╰─> [29 lines of output]
      running install
      running build
      got version from file /private/var/folders/yn/4byzlmls27n1sn4b19pwp6nm0000gn/T/pip-install-o9dwgbtj/llvmlite_14beb0db95e84b99a61cb1db7d4980bb/llvmlite/_version.py {'version': '0.31.0', 'full': 'fe7d985f6421d87f613bd414479d29d912771562'}
      running build_ext
      /Library/Frameworks/Python.framework/Versions/3.9/bin/python3 /private/var/folders/yn/4byzlmls27n1sn4b19pwp6nm0000gn/T/pip-install-o9dwgbtj/llvmlite_14beb0db95e84b99a61cb1db7d4980bb/ffi/build.py
      LLVM version... Traceback (most recent call last):
        File "/private/var/folders/yn/4byzlmls27n1sn4b19pwp6nm0000gn/T/pip-install-o9dwgbtj/llvmlite_14beb0db95e84b99a61cb1db7d4980bb/ffi/build.py", line 105, in main_posix
          out = subprocess.check_output([llvm_config, '--version'])
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 424, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 505, in run
          with Popen(*popenargs, **kwargs) as process:
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 951, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1821, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/private/var/folders/yn/4byzlmls27n1sn4b19pwp6nm0000gn/T/pip-install-o9dwgbtj/llvmlite_14beb0db95e84b99a61cb1db7d4980bb/ffi/build.py", line 168, in <module>
          main()
        File "/private/var/folders/yn/4byzlmls27n1sn4b19pwp6nm0000gn/T/pip-install-o9dwgbtj/llvmlite_14beb0db95e84b99a61cb1db7d4980bb/ffi/build.py", line 162, in main
          main_posix('osx', '.dylib')
        File "/private/var/folders/yn/4byzlmls27n1sn4b19pwp6nm0000gn/T/pip-install-o9dwgbtj/llvmlite_14beb0db95e84b99a61cb1db7d4980bb/ffi/build.py", line 107, in main_posix
          raise RuntimeError("%s failed executing, please point LLVM_CONFIG "
      RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
      error: command '/Library/Frameworks/Python.framework/Versions/3.9/bin/python3' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  WARNING: No metadata found in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages
  Rolling back uninstall of llvmlite
  Moving to /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/llvmlite-0.38.0.dist-info/
   from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/~lvmlite-0.38.0.dist-info
  Moving to /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/llvmlite/
   from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/~lvmlite
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> llvmlite

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
[wuyu@wuyudeMacBook-Pro Documents]$>

**Comment by kquark** [comment]
可能python版本太高，ttskit还没支持吧，用python37的环境试试。

**Comment by mingleLee** [comment]
mac python3.8也失败

**Comment by tx-anin** [comment]
mac os 12.3.1

**Comment by tx-anin** [comment]
mac os 12.3.1;

**Comment by yfq512** [comment]
@kquark 我就是py37的环境不行呀，能分享下你的环境和包么

**Comment by tx-anin** [comment]
macOS Monterey 12.4

**Comment by tx-anin** [comment]
macOS Monterey 12.4
Python3.7
正常

**Comment by zhajingwen** [comment]
我的是M1芯片也是可以的吧，可以的话，我虚拟环境测试下

**Comment by tx-anin** [comment]
我的是intel Core i5，M1没测
