### ISSUE TITLE
cannot import name '_replace_tone2_style_dict_to_default' from 'pypinyin.utils'

### ISSUE THREAD

**Issue by liuy52178** [kuangdd/ttskit#13]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/new/ly_test/ttskit-main/ttskit/__init__.py", line 50, in <module>
    import sdk_api
  File "/home/new/ly_test/ttskit-main/ttskit/sdk_api.py", line 37, in <module>
    from ttskit.mellotron import inference as mellotron
  File "/home/new/ly_test/ttskit-main/ttskit/mellotron/inference.py", line 26, in <module>
    from .data_utils import transform_mel, transform_text, transform_f0, transform_embed, transform_speaker
  File "/home/new/ly_test/ttskit-main/ttskit/mellotron/data_utils.py", line 24, in <module>
    from mellotron.text import text_to_sequence, cmudict
  File "/home/new/ly_test/ttskit-main/ttskit/mellotron/text/__init__.py", line 7, in <module>
    from phkit.chinese import text_to_sequence as text_to_sequence_phkit, sequence_to_text, text2pinyin
  File "/root/miniconda/envs/ly_tts_try/lib/python3.7/site-packages/phkit/__init__.py", line 94, in <module>
    from phkit.chinese import __doc__ as doc_chinese
  File "/root/miniconda/envs/ly_tts_try/lib/python3.7/site-packages/phkit/chinese/__init__.py", line 37, in <module>
    from .pinyin import text2pinyin, split_pinyin, change_diao
  File "/root/miniconda/envs/ly_tts_try/lib/python3.7/site-packages/phkit/chinese/pinyin.py", line 11, in <module>
    from ..pinyinkit import text2pinyin, split_pinyin, change_diao
  File "/root/miniconda/envs/ly_tts_try/lib/python3.7/site-packages/phkit/pinyinkit/__init__.py", line 6, in <module>
    from .core import lazy_pinyin, pinyin, slug, Style, initialize
  File "/root/miniconda/envs/ly_tts_try/lib/python3.7/site-packages/phkit/pinyinkit/core.py", line 20, in <module>
    from pypinyin.utils import _replace_tone2_style_dict_to_default
ImportError: cannot import name '_replace_tone2_style_dict_to_default' from 'pypinyin.utils' (/root/miniconda/envs/ly_tts_try/lib/python3.7/site-packages/pypinyin/utils.py)

请问ImportError: cannot import name '_replace_tone2_style_dict_to_default' from 'pypinyin.utils'  这个问题怎么解决呢？

**Comment by kquark** [comment]
我的也是这个问题，pypinyin版本太高，ttskit还没跟上，pypinyin回退到0.41.0即可：

pip install pypinyin==0.41.0
