### ISSUE TITLE
你好，这里有个错误，ImportError: cannot import name '_speaker_dict'

### ISSUE THREAD

**Issue by MoYuFly** [kuangdd/ttskit#24]
这里的resource 是ttskit包里面的resource吗，并没有看到这个函数
(pytorch1.6) C:\Users\Administrator>python E:\TTS\ttskit\myTest.py
Traceback (most recent call last):
  File "E:\TTS\ttskit\myTest.py", line 3, in <module>
    from ttskit import sdk_api
  File "E:\TTS\ttskit\ttskit\sdk_api.py", line 49, in <module>
    from .resource import _speaker_dict
ImportError: cannot import name '_speaker_dict'

**Comment by MoYuFly** [comment]
发现了，百度网盘下载的resource和 github拉下来的有所出入。
