### ISSUE TITLE
网页版快速使用流程(亲测有效)

### ISSUE THREAD

**Issue by Nekobaex** [kuangdd/ttskit#33]
1. 从 GitHub下载代码并解压，将文件夹 `ttskit-main` 作为自己的项目文件夹
2. 从百度网盘下载 `resource` 将其放到 `ttskit-main\ttskit` 文件夹中覆盖原有的 `resource` 文件夹
3. 以上是作者提供步骤的大致描述, 但有一个小问题
4. 实际上, 在替换过程中, `ttskit-main\ttskit\resoure\__init__.py` 不要替换
5. 或者 完全替换之后, 再把 github 下载的文件解压一份, 然后用那里面的 `resoure\__init__.py` 单独替换回来
6. 然后就在 `ttskit-main` 目录打开命令行, 输入并回车 `pip install -U ttskit`
7. pip 结束后, 在 `ttskit-main` 文件夹中建立一个 `demo.py` 文件, 并输入以下代码
    ```python
   from ttskit import http_server

    http_server.start_sever()```
 8. 然后在命令行中输入 py demo.py 
 9. 过一段时间, 命令行最下端出现一段网址, 将它复制到浏览器粘贴即可

**Comment by Nekobaex** [comment]
在网页版体验中, 第二个框框里可以填参数,
但注意, mode 参数的值为 rtvc 时, 
audio 参数的设置才有效,
audio 对应不同的人声,
列举如下(图片中): 
![image](https://user-images.githubusercontent.com/89440464/198684088-5ae66595-e7ce-424d-a950-757a213741e0.png)

**Comment by prz30** [comment]
不好意思，请问运行的时候显示缺少melgan.kuangdd.pt是为什么呢，我看网盘里也没有这个模型

**Comment by dingqiaolin** [comment]
怎么才能支持英文字母朗读呢

**Comment by alihua123** [comment]
请问linux可以吗

**Comment by steamfeifei** [comment]
语速可以调整吗？

**Comment by ListenQ** [comment]
> 1. 从 GitHub下载代码并解压，将文件夹 `ttskit-main` 作为自己的项目文件夹
> 2. 从百度网盘([下载地址](https://github.com/kuangdd/ttskit#%E8%B5%84%E6%BA%90)) 下载 `resource` 将其放到 `ttskit-main\ttskit` 文件夹中覆盖原有的 `resource` 文件夹
> 3. 以上是作者提供步骤的大致描述, 但有一个小问题
> 4. 实际上, 在替换过程中, `ttskit-main\ttskit\resoure\__init__.py` 不要替换
> 5. 或者 完全替换之后, 再把 github 下载的文件解压一份, 然后用那里面的 `resoure\__init__.py` 单独替换回来
> 6. 然后就在 `ttskit-main` 目录打开命令行, 输入并回车 `pip install -U ttskit`
> 7. pip 结束后, 在 `ttskit-main` 文件夹中建立一个 `demo.py` 文件, 并输入以下代码
>    ```python
>    from ttskit import http_server
>    
>    http_server.start_sever()```
>    ```
> 8. 然后在命令行中输入 py demo.py
> 9. 过一段时间, 命令行最下端出现一段网址, 将它复制到浏览器粘贴即可
> 10. 示例图片:
>     ![image](https://user-images.githubusercontent.com/89440464/198682638-d493815f-1029-4ab3-8731-a242d4c90cb6.png)
>     ![image](https://user-images.githubusercontent.com/89440464/198682772-21fa2d09-b78c-4f3c-a5ea-180914a45cd5.png)

请问 点击合成按钮后提示 Error: INTERNAL SERVER ERROR 是什么问题该如何解决？
运行的命令窗显示如下：
```
127.0.0.1 - - [2023-12-06 11:08:57] "GET /synthesize?text=%E6%AC%A2%E8%BF%8E%E4%BD%BF%E7%94%A8%E8%AF%AD%E9%9F%B3%E5%90%88%E6%88%90%E5%B7%A5%E5%85%B7%E7%AE%B1%EF%BC%8C%E8%AF%B7%E8%BE%93%E5%85%A5%E9%9C%80%E8%A6%81%E5%90%88%E6%88%90%E7%9A%84%E6%96%87%E6%9C%AC&kwargs=format%3A%20yaml%0Amode%3A%20mspk%0Aaudio%3A%2014%0Aspeaker%3A%20Aiyue%0Avocoder%3A%20melgan HTTP/1.1" 500 401 0.006207
ERROR:ttskit.http_server:Exception on /synthesize [GET]
Traceback (most recent call last):
  File "/home/zhangqi/miniconda3/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zhangqi/miniconda3/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zhangqi/miniconda3/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zhangqi/miniconda3/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zhangqi/tts/ttskit/ttskit-main/ttskit/http_server.py", line 118, in synthesize
    kwargs = yaml.load(kwargs_str)
             ^^^^^^^^^^^^^^^^^^^^^
TypeError: load() missing 1 required positional argument: 'Loader'
127.0.0.1 - - [2023-12-06 11:09:02] "GET /synthesize?text=%E4%BD%A0%E5%A5%BD&kwargs=format%3A%20yaml%0Amode%3A%20mspk%0Aaudio%3A%2014%0Aspeaker%3A%20Aiyue%0Avocoder%3A%20melgan HTTP/1.1" 500 401 0.002770
```
