### ISSUE TITLE
十几个字合成要1秒多时间，请问正常吗？

### ISSUE THREAD

**Issue by junceo** [kuangdd/ttskit#34]
在用某云提供的tts接口合成，基本在200毫秒内，ttskit能否做到500毫秒以内呢？

**Comment by renllll** [comment]
请问为啥我合成要十几秒而网页版快很多

**Comment by 118dz** [comment]
咋跑起来的我想问下，我就是直接install 按照他们的demo跑，直接报错

**Comment by junceo** [comment]
> 咋跑起来的我想问下，我就是直接install 按照他们的demo跑，直接报错

直接就能跑，有报错看报什么错

**Comment by 118dz** [comment]
> > 咋跑起来的我想问下，我就是直接install 按照他们的demo跑，直接报错
> 
> 直接就能跑，有报错看报什么错

  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
2023-08-16 16:32:03.533265: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-08-16 16:32:03.537254: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-08-16 16:32:03.654610: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-08-16 16:32:03.656874: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-08-16 16:32:06.883644: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
/home/dayao/work/tts_2/venv/lib/python3.8/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1042, in _handle_fromlist
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/dayao/work/tts_2/venv/lib/python3.8/site-packages/ttskit/sdk_api.py", line 45, in <module>
    from .mellotron import inference as mellotron
  File "/home/dayao/work/tts_2/venv/lib/python3.8/site-packages/ttskit/mellotron/inference.py", line 24, in <module>
    from .data_utils import TextMelLoader, TextMelCollate
  File "/home/dayao/work/tts_2/venv/lib/python3.8/site-packages/ttskit/mellotron/data_utils.py", line 24, in <module>
    from mellotron.text import text_to_sequence, cmudict
  File "/home/dayao/work/tts_2/venv/lib/python3.8/site-packages/ttskit/mellotron/text/__init__.py", line 7, in <module>
    from phkit.chinese import text_to_sequence as text_to_sequence_phkit, sequence_to_text, text2pinyin
  File "/home/dayao/work/tts_2/venv/lib/python3.8/site-packages/phkit/__init__.py", line 38, in <module>
    from .english import __doc__ as doc_english
  File "/home/dayao/work/tts_2/venv/lib/python3.8/site-packages/phkit/english/__init__.py", line 23, in <module>
    from . import cleaners
  File "/home/dayao/work/tts_2/venv/lib/python3.8/site-packages/phkit/english/cleaners.py", line 18, in <module>
    from .numbers import normalize_numbers
  File "/home/dayao/work/tts_2/venv/lib/python3.8/site-packages/phkit/english/numbers.py", line 3, in <module>
    import inflect
  File "/home/dayao/work/tts_2/venv/lib/python3.8/site-packages/inflect/__init__.py", line 75, in <module>
    from pydantic import Field
  File "/home/dayao/work/tts_2/venv/lib/python3.8/site-packages/pydantic/__init__.py", line 13, in <module>
    from . import dataclasses
  File "/home/dayao/work/tts_2/venv/lib/python3.8/site-packages/pydantic/dataclasses.py", line 11, in <module>
    from ._internal import _config, _decorators, _typing_extra
  File "/home/dayao/work/tts_2/venv/lib/python3.8/site-packages/pydantic/_internal/_decorators.py", line 15, in <module>
    from ..fields import ComputedFieldInfo
  File "/home/dayao/work/tts_2/venv/lib/python3.8/site-packages/pydantic/fields.py", line 18, in <module>
    from . import types
  File "/home/dayao/work/tts_2/venv/lib/python3.8/site-packages/pydantic/types.py", line 34, in <module>
    from ._internal import (
  File "/home/dayao/work/tts_2/venv/lib/python3.8/site-packages/pydantic/_internal/_fields.py", line 13, in <module>
    from . import _typing_extra
  File "/home/dayao/work/tts_2/venv/lib/python3.8/site-packages/pydantic/_internal/_typing_extra.py", line 13, in <module>
    from typing_extensions import Annotated, Final, Literal, TypeAliasType, TypeGuard, get_args, get_origin
ImportError: cannot import name 'TypeAliasType' from 'typing_extensions' (/home/dayao/work/tts_2/venv/lib/python3.8/site-packages/typing_extensions.py)

Process finished with exit code 1

**Comment by 118dz** [comment]
warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
2023-08-16 16:32:03.533265: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-08-16 16:32:03.537254: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-08-16 16:32:03.654610: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-08-16 16:32:03.656874: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-08-16 16:32:06.883644: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
/home/dy/work/tts_2/venv/lib/python3.8/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1042, in _handle_fromlist
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/dy/work/tts_2/venv/lib/python3.8/site-packages/ttskit/sdk_api.py", line 45, in <module>
    from .mellotron import inference as mellotron
  File "/home/dy/work/tts_2/venv/lib/python3.8/site-packages/ttskit/mellotron/inference.py", line 24, in <module>
    from .data_utils import TextMelLoader, TextMelCollate
  File "/home/dy/work/tts_2/venv/lib/python3.8/site-packages/ttskit/mellotron/data_utils.py", line 24, in <module>
    from mellotron.text import text_to_sequence, cmudict
  File "/home/dy/work/tts_2/venv/lib/python3.8/site-packages/ttskit/mellotron/text/__init__.py", line 7, in <module>
    from phkit.chinese import text_to_sequence as text_to_sequence_phkit, sequence_to_text, text2pinyin
  File "/home/dy/work/tts_2/venv/lib/python3.8/site-packages/phkit/__init__.py", line 38, in <module>
    from .english import __doc__ as doc_english
  File "/home/dy/work/tts_2/venv/lib/python3.8/site-packages/phkit/english/__init__.py", line 23, in <module>
    from . import cleaners
  File "/home/dy/work/tts_2/venv/lib/python3.8/site-packages/phkit/english/cleaners.py", line 18, in <module>
    from .numbers import normalize_numbers
  File "/home/dy/work/tts_2/venv/lib/python3.8/site-packages/phkit/english/numbers.py", line 3, in <module>
    import inflect
  File "/home/dy/work/tts_2/venv/lib/python3.8/site-packages/inflect/__init__.py", line 75, in <module>
    from pydantic import Field
  File "/home/dy/work/tts_2/venv/lib/python3.8/site-packages/pydantic/__init__.py", line 13, in <module>
    from . import dataclasses
  File "/home/dy/work/tts_2/venv/lib/python3.8/site-packages/pydantic/dataclasses.py", line 11, in <module>
    from ._internal import _config, _decorators, _typing_extra
  File "/home/dy/work/tts_2/venv/lib/python3.8/site-packages/pydantic/_internal/_decorators.py", line 15, in <module>
    from ..fields import ComputedFieldInfo
  File "/home/dy/work/tts_2/venv/lib/python3.8/site-packages/pydantic/fields.py", line 18, in <module>
    from . import types
  File "/home/dy/work/tts_2/venv/lib/python3.8/site-packages/pydantic/types.py", line 34, in <module>
    from ._internal import (
  File "/home/dy/work/tts_2/venv/lib/python3.8/site-packages/pydantic/_internal/_fields.py", line 13, in <module>
    from . import _typing_extra
  File "/home/dy/work/tts_2/venv/lib/python3.8/site-packages/pydantic/_internal/_typing_extra.py", line 13, in <module>
    from typing_extensions import Annotated, Final, Literal, TypeAliasType, TypeGuard, get_args, get_origin
ImportError: cannot import name 'TypeAliasType' from 'typing_extensions' (/home/dy/work/tts_2/venv/lib/python3.8/site-packages/typing_extensions.py)这个是报错信息

**Comment by junceo** [comment]
> > > 咋跑起来的我想问下，我就是直接install 按照他们的demo跑，直接报错
> > 
> > 
> > 直接就能跑，有报错看报什么错
> 
> warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning) 2023-08-16 16:32:03.533265: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`. 2023-08-16 16:32:03.537254: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used. 2023-08-16 16:32:03.654610: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used. 2023-08-16 16:32:03.656874: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations. To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags. 2023-08-16 16:32:06.883644: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT /home/dayao/work/tts_2/venv/lib/python3.8/site-packages/torch/cuda/**init**.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at /pytorch/c10/cuda/CUDAFunctions.cpp:100.) return torch._C._cuda_getDeviceCount() > 0 Traceback (most recent call last): File "", line 1042, in _handle_fromlist File "", line 219, in _call_with_frames_removed File "/home/dayao/work/tts_2/venv/lib/python3.8/site-packages/ttskit/sdk_api.py", line 45, in from .mellotron import inference as mellotron File "/home/dayao/work/tts_2/venv/lib/python3.8/site-packages/ttskit/mellotron/inference.py", line 24, in from .data_utils import TextMelLoader, TextMelCollate File "/home/dayao/work/tts_2/venv/lib/python3.8/site-packages/ttskit/mellotron/data_utils.py", line 24, in from mellotron.text import text_to_sequence, cmudict File "/home/dayao/work/tts_2/venv/lib/python3.8/site-packages/ttskit/mellotron/text/**init**.py", line 7, in from phkit.chinese import text_to_sequence as text_to_sequence_phkit, sequence_to_text, text2pinyin File "/home/dayao/work/tts_2/venv/lib/python3.8/site-packages/phkit/**init**.py", line 38, in from .english import **doc** as doc_english File "/home/dayao/work/tts_2/venv/lib/python3.8/site-packages/phkit/english/**init**.py", line 23, in from . import cleaners File "/home/dayao/work/tts_2/venv/lib/python3.8/site-packages/phkit/english/cleaners.py", line 18, in from .numbers import normalize_numbers File "/home/dayao/work/tts_2/venv/lib/python3.8/site-packages/phkit/english/numbers.py", line 3, in import inflect File "/home/dayao/work/tts_2/venv/lib/python3.8/site-packages/inflect/**init**.py", line 75, in from pydantic import Field File "/home/dayao/work/tts_2/venv/lib/python3.8/site-packages/pydantic/**init**.py", line 13, in from . import dataclasses File "/home/dayao/work/tts_2/venv/lib/python3.8/site-packages/pydantic/dataclasses.py", line 11, in from ._internal import _config, _decorators, _typing_extra File "/home/dayao/work/tts_2/venv/lib/python3.8/site-packages/pydantic/_internal/_decorators.py", line 15, in from ..fields import ComputedFieldInfo File "/home/dayao/work/tts_2/venv/lib/python3.8/site-packages/pydantic/fields.py", line 18, in from . import types File "/home/dayao/work/tts_2/venv/lib/python3.8/site-packages/pydantic/types.py", line 34, in from ._internal import ( File "/home/dayao/work/tts_2/venv/lib/python3.8/site-packages/pydantic/_internal/_fields.py", line 13, in from . import _typing_extra File "/home/dayao/work/tts_2/venv/lib/python3.8/site-packages/pydantic/_internal/_typing_extra.py", line 13, in from typing_extensions import Annotated, Final, Literal, TypeAliasType, TypeGuard, get_args, get_origin ImportError: cannot import name 'TypeAliasType' from 'typing_extensions' (/home/dayao/work/tts_2/venv/lib/python3.8/site-packages/typing_extensions.py)
> 
> Process finished with exit code 1



> warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
> 2023-08-16 16:32:03.533265: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
> 2023-08-16 16:32:03.537254: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
> 2023-08-16 16:32:03.654610: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
> 2023-08-16 16:32:03.656874: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
> To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
> 2023-08-16 16:32:06.883644: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
> /home/dy/work/tts_2/venv/lib/python3.8/site-packages/torch/cuda/**init**.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
> return torch._C._cuda_getDeviceCount() > 0
> Traceback (most recent call last):
> File "", line 1042, in _handle_fromlist
> File "", line 219, in _call_with_frames_removed
> File "/home/dy/work/tts_2/venv/lib/python3.8/site-packages/ttskit/sdk_api.py", line 45, in 
> from .mellotron import inference as mellotron
> File "/home/dy/work/tts_2/venv/lib/python3.8/site-packages/ttskit/mellotron/inference.py", line 24, in 
> from .data_utils import TextMelLoader, TextMelCollate
> File "/home/dy/work/tts_2/venv/lib/python3.8/site-packages/ttskit/mellotron/data_utils.py", line 24, in 
> from mellotron.text import text_to_sequence, cmudict
> File "/home/dy/work/tts_2/venv/lib/python3.8/site-packages/ttskit/mellotron/text/**init**.py", line 7, in 
> from phkit.chinese import text_to_sequence as text_to_sequence_phkit, sequence_to_text, text2pinyin
> File "/home/dy/work/tts_2/venv/lib/python3.8/site-packages/phkit/**init**.py", line 38, in 
> from .english import **doc** as doc_english
> File "/home/dy/work/tts_2/venv/lib/python3.8/site-packages/phkit/english/**init**.py", line 23, in 
> from . import cleaners
> File "/home/dy/work/tts_2/venv/lib/python3.8/site-packages/phkit/english/cleaners.py", line 18, in 
> from .numbers import normalize_numbers
> File "/home/dy/work/tts_2/venv/lib/python3.8/site-packages/phkit/english/numbers.py", line 3, in 
> import inflect
> File "/home/dy/work/tts_2/venv/lib/python3.8/site-packages/inflect/**init**.py", line 75, in 
> from pydantic import Field
> File "/home/dy/work/tts_2/venv/lib/python3.8/site-packages/pydantic/**init**.py", line 13, in 
> from . import dataclasses
> File "/home/dy/work/tts_2/venv/lib/python3.8/site-packages/pydantic/dataclasses.py", line 11, in 
> from ._internal import _config, _decorators, _typing_extra
> File "/home/dy/work/tts_2/venv/lib/python3.8/site-packages/pydantic/_internal/_decorators.py", line 15, in 
> from ..fields import ComputedFieldInfo
> File "/home/dy/work/tts_2/venv/lib/python3.8/site-packages/pydantic/fields.py", line 18, in 
> from . import types
> File "/home/dy/work/tts_2/venv/lib/python3.8/site-packages/pydantic/types.py", line 34, in 
> from ._internal import (
> File "/home/dy/work/tts_2/venv/lib/python3.8/site-packages/pydantic/_internal/_fields.py", line 13, in 
> from . import _typing_extra
> File "/home/dy/work/tts_2/venv/lib/python3.8/site-packages/pydantic/_internal/_typing_extra.py", line 13, in 
> from typing_extensions import Annotated, Final, Literal, TypeAliasType, TypeGuard, get_args, get_origin
> ImportError: cannot import name 'TypeAliasType' from 'typing_extensions' (/home/dy/work/tts_2/venv/lib/python3.8/site-packages/typing_extensions.py)这个是报错信息

改为CPU模式试试

**Comment by 118dz** [comment]
在哪改

**Comment by 118dz** [comment]
from ttskit import sdk_api

if __name__ == "__main__":
    wav = sdk_api.tts_sdk(text='在哪改',audio='24',output="home/dy/work/zhhh.wav")
上面是测试的代码 这个地方要怎么修改调整
